Fix TypeError with css-split-webpack-plugin (#160)
Using the `--replace` option along with source maps causes the
css-split-webpack-plugin to have problems:

```sh
TypeError: Cannot read property 'toString' of undefined
    at /Users/k/p/kununu/node_modules/css-split-webpack-plugin/dist/index.js:170:73
    at Array.map (native)
    at /Users/k/p/kununu/node_modules/css-split-webpack-plugin/dist/index.js:166:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

This can be avoided by disabling the source map.